export const SPEED_OPT_MEDIUM_NODE_THRESHOLD = 50;
export const SPEED_OPT_STRONG_NODE_THRESHOLD = 100;

export const PROGRESSIVE_EDGE_CHUNK_SIZE = 5;
export const PROGRESSIVE_EDGE_BUDGET_MS = 8;

export const HEAVY_MODE_MAX_TICKS = 55;
export const LOW_QUALITY_SPLINE_EDGE_THRESHOLD = 100;
