FROM harbor.vimpelcom.ru/common/nginx-uno

COPY /nginx/  /etc/nginx/
COPY /scripts/99-replace-www-env.sh /docker-entrypoint.d/99-replace-www-env.sh
COPY /build/  /www/
RUN chown -R nginx:root /www && chmod o+r /www -R && chmod +x /docker-entrypoint.d/99-replace-www-env.sh
USER nginx

# defaults for the image, kindly remind to add in the scripts/99-replace-www-env.sh crutch

# for sibur internal
# ENV FLAG_IS_DEMO_STAND=true
# ENV FLAG_AUTHENTIK_URL='https://sibur-demo-0.arch-code-demo.cloud.vimpelcom.ru'
# ENV FLAG_API_URL='http://sibur-demo.arch-code-demo.cloud.vimpelcom.ru:9081/api-gateway/'

# for sibur external
# ENV FLAG_IS_DEMO_STAND=true
# ENV FLAG_AUTHENTIK_URL='https://auth.ai-platform.pro'
# ENV FLAG_API_URL='https://api.beeatlas.ai-platform.pro/api-gateway/'

ENV FLAG_IS_DEMO_STAND=false
ENV FLAG_IS_FUNC=false
ENV FLAG_AUTHENTIK_URL='http://authentik:8080'
ENV FLAG_API_URL=''

# defaults for nginx\site.d\http-frontend.conf.in.env
ENV NGINX_LOCATION_API_GATEWAY='http://gateway:8080'
ENV NGINX_LOCATION_API='http://backend:8080'
ENV NGINX_LOCATION_API_GATEWAY_ADDITIONAL_PARAMS=''
ENV NGINX_LOCATION_API_ADDITIONAL_PARAMS=''
