FROM harbor.vimpelcom.ru/common/nginx-uno

COPY /nginx/  /etc/nginx/
COPY /scripts/99-replace-www-env.sh /docker-entrypoint.d/99-replace-www-env.sh
COPY /build/  /www/
RUN chown -R nginx:root /www && chmod o+r /www -R && chmod +x /docker-entrypoint.d/99-replace-www-env.sh
USER nginx

# defaults for the image, kindly remind to add in the scripts/99-replace-www-env.sh crutch

ENV FLAG_IS_PROD=false
ENV FLAG_IS_DEMO_STAND=false
ENV FLAG_IS_FUNC=false
ENV FLAG_AUTHENTIK_URL='http://authentik:8080'
ENV FLAG_API_URL=''
ENV FLAG_DOC_SERVICE_URL='https://beeatlas-doc-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru/'
ENV FLAG_WEBIDE_URL='https://vs-code-server-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru/'
ENV FLAG_AUTHENTIK_CLIENT_ID=''
ENV FLAG_EAUTH_URL='https://eauth-dev.ess-test.vimpelcom.ru'

# defaults for nginx\site.d\http-frontend.conf.in.env
ENV NGINX_LOCATION_API_GATEWAY='http://gateway:8080'
ENV NGINX_LOCATION_API='http://backend:8080'
ENV NGINX_LOCATION_API_GATEWAY_ADDITIONAL_PARAMS=''
ENV NGINX_LOCATION_API_ADDITIONAL_PARAMS=''
