#!/usr/bin/env bash

cat <<EOF > /www/env/env
FLAG_IS_PROD='${FLAG_IS_PROD}'
FLAG_IS_DEMO_STAND='${FLAG_IS_DEMO_STAND}'
FLAG_IS_FUNC='${FLAG_IS_FUNC}'
FLAG_AUTHENTIK_URL='${FLAG_AUTHENTIK_URL}'
FLAG_API_URL='${FLAG_API_URL}'
FLAG_DOC_SERVICE_URL='${FLAG_DOC_SERVICE_URL}'
FLAG_WEBIDE_URL='${FLAG_WEBIDE_URL}'
FLAG_AUTHENTIK_CLIENT_ID='${FLAG_AUTHENTIK_CLIENT_ID}'
FLAG_EAUTH_URL='${FLAG_EAUTH_URL}'
EOF

cat /www/env/env
# develop exampele: add line FLAG_NAME='${FLAG_NAME}'
# keep " ' " as in the example