export enum PageId {
    AnalyticalReport = 'analytical-report',
    ApplicationView = 'application-view',
    BiLibrary = 'bi-library',
    BiView = 'bi-view',
    CjLibrary = 'cj-library',
    CustomerJourney = 'customer-journey',
    E2eView = 'e2e-view',
    FdmView = 'fdm-view',
    FdmSearch = 'fdm-search',
    Impact = 'impact',
    LifeSituations = 'life-situations',
    MapView = 'map-view',
    PatternView = 'pattern-view',
    Patterns = 'patterns',
    PersonalMapView = 'personal-map-view',
    TechRadar = 'tech-radar',
    TechnologyView = 'technology-view',
}

export const PAGE_ID_LABELS: Record<PageId, string> = {
    [PageId.AnalyticalReport]: 'Аналитический отчёт',
    [PageId.ApplicationView]: 'Приложение',
    [PageId.BiLibrary]: 'Библиотека BI',
    [PageId.BiView]: 'BI',
    [PageId.CjLibrary]: 'Библиотека CJ',
    [PageId.CustomerJourney]: 'CJ',
    [PageId.E2eView]: 'E2E сценарии',
    [PageId.FdmView]: 'ФДМ',
    [PageId.FdmSearch]: 'Поиск по ФДМ',
    [PageId.Impact]: 'Архитектура компании',
    [PageId.LifeSituations]: 'Жизненные ситуации',
    [PageId.MapView]: 'Карты возможностей',
    [PageId.PatternView]: 'Паттерн',
    [PageId.Patterns]: 'Паттерны',
    [PageId.PersonalMapView]: 'Персональная карта',
    [PageId.TechRadar]: 'Технорадар',
    [PageId.TechnologyView]: 'Технология',
};
