securityContext:
  readOnlyRootFilesystem: false
podAnnotations:
  vault.security.banzaicloud.io/vault-role: "false"
  vault.security.banzaicloud.io/vault-path: "false"
  vault.security.banzaicloud.io/vault-addr: "false"
  vault.security.banzaicloud.io/vault-skip-verify: "false"
  vault.security.banzaicloud.io/vault-agent: "false"
  prometheus.io/path: "false"
  prometheus.io/scheme: "false"
  prometheus.io/scrape: "false"
  prometheus.io/port: "false"

ingress:
  hosts:
    - host: "changehost"
      paths:
      - path: /
        pathType: ImplementationSpecific
    - host: "eafdmmart-func.apps.mn-kp01.vimpelcom.ru"
      paths:
      - path: /api/
        pathType: ImplementationSpecific
        serviceName: eafdmmart-backend-func-service
        servicePort: "8080"
      - path: /
        pathType: ImplementationSpecific
