podAnnotations:
  vault.security.banzaicloud.io/vault-role: "false"
  vault.security.banzaicloud.io/vault-path: "false"
  vault.security.banzaicloud.io/vault-addr: "false"
  vault.security.banzaicloud.io/vault-skip-verify: "false"
  vault.security.banzaicloud.io/vault-agent: "false"
  prometheus.io/path: "false"
  prometheus.io/scheme: "false"
  prometheus.io/scrape: "false"
  prometheus.io/port: "false"

ingress:
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($host = "tr.vimpelcom.ru") {
        rewrite / https://beeatlas.vimpelcom.ru/models/tech-radar permanent;
      }
      if ($host = "techradar.vimpelcom.ru") {
        rewrite / https://beeatlas.vimpelcom.ru/models/tech-radar permanent;
      }

  hosts:
    - host: "changehost"
      paths:
      - path: /
        pathType: ImplementationSpecific
    - host: "eafdmmart-prod.apps.yd-k03.vimpelcom.ru"
      paths:
      - path: /api/
        pathType: ImplementationSpecific
        serviceName: eafdmmart-backend-prod-service
        servicePort: "8080"
      - path: /
        pathType: ImplementationSpecific
    - host: "beeatlas.vimpelcom.ru"
      paths:
      - path: /api/
        pathType: ImplementationSpecific
        serviceName: eafdmmart-backend-prod-service
        servicePort: "8080"
      - path: /
        pathType: ImplementationSpecific
    - host: "techradar.vimpelcom.ru"
      paths:
      - path: /api/
        pathType: ImplementationSpecific
        serviceName: eafdmmart-backend-prod-service
        servicePort: "8080"
      - path: /
        pathType: ImplementationSpecific
    - host: "tr.vimpelcom.ru"
      paths:
      - path: /api/
        pathType: ImplementationSpecific
        serviceName: eafdmmart-backend-prod-service
        servicePort: "8080"
      - path: /
        pathType: ImplementationSpecific

  tls:
    - hosts:
        - beeatlas.vimpelcom.ru
      secretName: beeatlas-tls
    - hosts:
        - tr.vimpelcom.ru
      secretName: tr-tls
    - hosts:
        - techradar.vimpelcom.ru
      secretName: techradar-tls


replicaCount: 3