ingress:
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($host = "tr.vimpelcom.ru") {
        rewrite / https://beeatlas.vimpelcom.ru/models/tech-radar permanent;
      }
      if ($host = "techradar.vimpelcom.ru") {
        rewrite / https://beeatlas.vimpelcom.ru/models/tech-radar permanent;
      }

  className: ingress-waf

  hosts:
    - host: "changehost"
      paths:
      - path: /
        pathType: ImplementationSpecific
    - host: "beeatlas.vimpelcom.ru"
      paths:
      - path: /
        pathType: ImplementationSpecific
    - host: "techradar.vimpelcom.ru"
      paths:
      - path: /
        pathType: ImplementationSpecific
    - host: "tr.vimpelcom.ru"
      paths:
      - path: /
        pathType: ImplementationSpecific

  tls:
    - hosts:
        - beeatlas.vimpelcom.ru
      secretName: beeatlas-tls
    - hosts:
        - tr.vimpelcom.ru
      secretName: tr-tls
    - hosts:
        - techradar.vimpelcom.ru
      secretName: techradar-tls


replicaCount: 1