podAnnotations:
  vault.security.banzaicloud.io/vault-role: "false"
  vault.security.banzaicloud.io/vault-path: "false"
  vault.security.banzaicloud.io/vault-addr: "false"
  vault.security.banzaicloud.io/vault-skip-verify: "false"
  vault.security.banzaicloud.io/vault-agent: "false"
  prometheus.io/path: "false"
  prometheus.io/scheme: "false"
  prometheus.io/scrape: "false"
  prometheus.io/port: "false"

podAnnotations:
  vault.security.banzaicloud.io/vault-addr: "https://vault-test.vimpelcom.ru/"

ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  hosts:
    - host: "changehost"
      paths:
      - path: /
        pathType: ImplementationSpecific
    - host: "eafdmmart-dev.apps.yd-m6-kt22.vimpelcom.ru"
      paths:
      - path: /
        pathType: ImplementationSpecific

env:
  NGINX_LOCATION_API_GATEWAY: http://eafdmmart-dev-fdm-gateway
  NGINX_LOCATION_API: http://eafdmmart-backend-dev-service:8080
  NGINX_LOCATION_API_GATEWAY_ADDITIONAL_PARAMS: ''
  NGINX_LOCATION_API_ADDITIONAL_PARAMS: ''

writableDir:
  enabled: true
  path: /www/env
