podAnnotations:
  vault.security.banzaicloud.io/vault-role: "false"
  vault.security.banzaicloud.io/vault-path: "false"
  vault.security.banzaicloud.io/vault-addr: "false"
  vault.security.banzaicloud.io/vault-skip-verify: "false"
  vault.security.banzaicloud.io/vault-agent: "false"
  prometheus.io/path: "false"
  prometheus.io/scheme: "false"
  prometheus.io/scrape: "false"
  prometheus.io/port: "false"
  
ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  hosts:
    - host: "changehost"
      paths:
      - path: /
        pathType: ImplementationSpecific
    - host: "eafdmmart-e2e.apps.yd-m6-kt22.vimpelcom.ru"
      paths:
      - path: /
        pathType: ImplementationSpecific

env:
  NGINX_LOCATION_API_GATEWAY: http://fdm-gateway-e2e-service:8080
  NGINX_LOCATION_API: http://eafdmmart-backend-e2e-service:8080
  NGINX_LOCATION_API_GATEWAY_ADDITIONAL_PARAMS: ''
  NGINX_LOCATION_API_ADDITIONAL_PARAMS: ''
