export const theme = {
    colors: {
        // divider: 'var(--color-divider)',
        // textActive: 'var(--color-text-active)',
        // textActiveNoTheme: 'rgba(9, 11, 22, 0.94)',
        // textActiveInverse: 'var(--color-text-active-inverse)',
        // textInactive: 'var(--color-text-inactive)',
        // textLogo: 'var(--color-text-logo)',
        // textLink: 'var(--color-text-link)',
        // textInfo: 'var(--color-status-info)',
        // textDisabled: 'var(--color-text-disabled)',
        // magenta: 'var(--color-accent-magenta-background)',
        // teal: 'var(--color-accent-teal-background)',
        // lemon: 'var(--color-accent-lemon-background)',
        // info: 'var(--color-status-info-background)',
        // brandYellow: 'var(--color-palette-yellow-600)',
        // warning: 'var(--color-status-warning)',
        // success: 'var(--color-status-success)',
        // chartGreen: 'var(--color-chart-green-active)',
        // chartRed: 'var(--color-chart-red-active)',
        // chartBlue: 'var(--color-chart-blue-active)',
        // chartGrey: 'var(--color-chart-grey-active)',
        // scroll: 'var(--color-utilities-scroll)',
        // borderError: 'var(--color-border-error)',
    },

    zIndex: {
        sidebar: 1,
        tableHead: 2,
        header: 3,
        dropdown: 4,
        modal: 5,
        tooltip: 6,
    },
};
