const IS_DEV = process.env.NODE_ENV !== 'production';

const PREFIX_GATEWAY = '/api-gateway/';
const PREFIX_GATEWAY_PRODUCT = '/product/api/';
const PREFIX_GATEWAY_ARCH_GRAPH = '/arch-graph/api/';
const PREFIX_GATEWAY_CAPABILITY = '/capability/api/';
const PREFIX_STRUCTURIZR = '/structurizr-backend/';
const PREFIX_GATEWAY_GRAPH_VALIDATOR = '/graph-validator/api/';
const PREFIX_GATEWAY_CX = '/cx/api/';
const PREFIX_GATEWAY_CAMUNDA = '/camunda/';
const PREFIX_GATEWAY_AMBASSADOR = '/ambassador/';
const PREFIX_OBS_DASHBOARD = '/obs-dashboard/api/';
const PREFIX_GATEWAY_SEQUENCE = '/sequence-backend/sequence/';
const PREFIX_GATEWAY_STAGING_SEQUENCE = '/staging-sequence/';
const PREFIX_GATEWAY_DASHBOARD_SERVICE = '/dashboard-service/';
const PREFIX_GATEWAY_USER = '/user/api/';
const PREFIX_GATEWAY_FF = '/ff/api/';

const GATEWAY_DIRECT_LINK = `${window.FEATURE_FLAGS.FLAG_API_URL}${PREFIX_GATEWAY}`;
const GATEWAY_DIRECT_PRODUCT_LINK = `${window.FEATURE_FLAGS.FLAG_API_URL}${PREFIX_GATEWAY_PRODUCT}`;
const GATEWAY_DIRECT_ARCH_GRAPH_LINK = `${window.FEATURE_FLAGS.FLAG_API_URL}${PREFIX_GATEWAY_ARCH_GRAPH}`;
const GATEWAY_DIRECT_CAPABILITY_LINK = `${window.FEATURE_FLAGS.FLAG_API_URL}${PREFIX_GATEWAY_CAPABILITY}`;
const GATEWAY_DIRECT_STRUCTURIZR_LINK = `${window.FEATURE_FLAGS.FLAG_API_URL}${PREFIX_STRUCTURIZR}`;
const GATEWAY_DIRECT_GRAPH_VALIDATOR_LINK = `${window.FEATURE_FLAGS.FLAG_API_URL}${PREFIX_GATEWAY_GRAPH_VALIDATOR}`;
const GATEWAY_DIRECT_CX_LINK = `${window.FEATURE_FLAGS.FLAG_API_URL}${PREFIX_GATEWAY_CX}`;
const GATEWAY_DIRECT_CAMUNDA_LINK = `${window.FEATURE_FLAGS.FLAG_API_URL}${PREFIX_GATEWAY_CAMUNDA}`;
const GATEWAY_DIRECT_AMBASSADOR_LINK = `${window.FEATURE_FLAGS.FLAG_API_URL}${PREFIX_GATEWAY_AMBASSADOR}`;
const GATEWAY_DIRECT_OBS_DASHBOARD_LINK = `${window.FEATURE_FLAGS.FLAG_API_URL}${PREFIX_OBS_DASHBOARD}`;
const GATEWAY_DIRECT_SEQUENCE_LINK = `${window.FEATURE_FLAGS.FLAG_API_URL}${PREFIX_GATEWAY_SEQUENCE}`;
const GATEWAY_DIRECT_STAGING_SEQUENCE_LINK = `${window.FEATURE_FLAGS.FLAG_API_URL}${PREFIX_GATEWAY_STAGING_SEQUENCE}`;
const GATEWAY_DIRECT_DASHBOARD_SERVICE_LINK = `${window.FEATURE_FLAGS.FLAG_API_URL}${PREFIX_GATEWAY_DASHBOARD_SERVICE}`;
const GATEWAY_DIRECT_USER_LINK = `${window.FEATURE_FLAGS.FLAG_API_URL}${PREFIX_GATEWAY_USER}`;
const GATEWAY_DIRECT_FF_LINK = `${window.FEATURE_FLAGS.FLAG_API_URL}${PREFIX_GATEWAY_FF}`;

export const GATEWAY_URL = IS_DEV ? GATEWAY_DIRECT_LINK : PREFIX_GATEWAY;
export const GATEWAY_PRODUCT_URL = IS_DEV ? GATEWAY_DIRECT_PRODUCT_LINK : PREFIX_GATEWAY_PRODUCT;
export const GATEWAY_ARCH_GRAPH_URL = IS_DEV
    ? GATEWAY_DIRECT_ARCH_GRAPH_LINK
    : PREFIX_GATEWAY_ARCH_GRAPH;
export const GATEWAY_CAPABILITY_URL = IS_DEV
    ? GATEWAY_DIRECT_CAPABILITY_LINK
    : PREFIX_GATEWAY_CAPABILITY;
export const GATEWAY_STRUCTURIZR_URL = IS_DEV
    ? GATEWAY_DIRECT_STRUCTURIZR_LINK
    : PREFIX_STRUCTURIZR;
export const GATEWAY_GRAPH_VALIDATOR_URL = IS_DEV
    ? GATEWAY_DIRECT_GRAPH_VALIDATOR_LINK
    : PREFIX_GATEWAY_GRAPH_VALIDATOR;
export const GATEWAY_CX_URL = IS_DEV ? GATEWAY_DIRECT_CX_LINK : PREFIX_GATEWAY_CX;
export const GATEWAY_CAMUNDA_URL = IS_DEV ? GATEWAY_DIRECT_CAMUNDA_LINK : PREFIX_GATEWAY_CAMUNDA;
export const GATEWAY_AMBASSADOR_URL = IS_DEV
    ? GATEWAY_DIRECT_AMBASSADOR_LINK
    : PREFIX_GATEWAY_AMBASSADOR;
export const GATEWAY_OBS_DASHBOARD_URL = IS_DEV
    ? GATEWAY_DIRECT_OBS_DASHBOARD_LINK
    : PREFIX_OBS_DASHBOARD;
export const GATEWAY_SEQUENCE_DIAGRAM_URL = IS_DEV
    ? GATEWAY_DIRECT_SEQUENCE_LINK
    : PREFIX_GATEWAY_SEQUENCE;
export const GATEWAY_STAGING_SEQUENCE_URL = IS_DEV
    ? GATEWAY_DIRECT_STAGING_SEQUENCE_LINK
    : PREFIX_GATEWAY_STAGING_SEQUENCE;
export const GATEWAY_DASHBOARD_SERVICE_URL = IS_DEV
    ? GATEWAY_DIRECT_DASHBOARD_SERVICE_LINK
    : PREFIX_GATEWAY_DASHBOARD_SERVICE;
export const GATEWAY_USER_URL = IS_DEV ? GATEWAY_DIRECT_USER_LINK : PREFIX_GATEWAY_USER;
export const GATEWAY_FF_URL = IS_DEV ? GATEWAY_DIRECT_FF_LINK : PREFIX_GATEWAY_FF;

export const MOCK_PRODUCT_ID = 1;
