
mkdir -p /www/env

cat <<EOF > /www/env/env
FLAG_IS_PROD='${FLAG_IS_PROD}'
FLAG_IS_DEMO_STAND='${FLAG_IS_DEMO_STAND}'
FLAG_SHOW_TOP_BANNER='${FLAG_SHOW_TOP_BANNER}'
FLAG_AUTHENTIK_URL='${FLAG_AUTHENTIK_URL}'
FLAG_API_URL='${FLAG_API_URL}'
FLAG_DOC_SERVICE_URL='${FLAG_DOC_SERVICE_URL}'
FLAG_WEBIDE_URL='${FLAG_WEBIDE_URL}'
FLAG_AUTHENTIK_CLIENT_ID='${FLAG_AUTHENTIK_CLIENT_ID}'
FLAG_EAUTH_URL='${FLAG_EAUTH_URL}'
FLAG_TEMPLATE_URL='${FLAG_TEMPLATE_URL}'
FLAG_DASHBOARD_URL='${FLAG_DASHBOARD_URL}'
EOF

cat /www/env/env
