export const defautltViewBox = { x: -45, y: -45, width: 90, height: 90 };

export const defautltTitlesTop = { hold: 0, assess: 79, trial: 155, adopt: 236 };

export const testData = [
    {
        label: 'Sparx EA',
        quadrant: 2,
        ring: 0,
        link: 'https://sparxsystems.com/',
    },
    {
        label: 'draw.io',
        quadrant: 2,
        ring: 0,
        link: 'https://www.draw.io/',
    },
    {
        label: 'plantuml',
        quadrant: 2,
        ring: 1,
        link: 'https://plantuml.com/',
    },
    {
        label: 'Kafka',
        quadrant: 3,
        ring: 0,
        link: 'https://kafka.apache.org/',
    },
    {
        label: 'RabbitMQ',
        quadrant: 3,
        ring: 0,
        link: 'https://www.rabbitmq.com/',
    },
    {
        label: 'Oracle EE',
        quadrant: 3,
        ring: 3,
        link: '',
    },
    {
        label: 'MS SQL Server',
        quadrant: 3,
        ring: 3,
        link: '',
    },
    {
        label: 'PostgreSQL',
        quadrant: 3,
        ring: 0,
        link: 'https://www.postgresql.org/',
    },
    {
        label: 'MongoDB',
        quadrant: 3,
        ring: 3,
        link: 'https://www.mongodb.com/',
    },
    {
        label: 'Hbase',
        quadrant: 3,
        ring: 2,
        link: 'https://hbase.apache.org/',
    },
    {
        label: 'Cassandra',
        quadrant: 3,
        ring: 2,
        link: 'https://cassandra.apache.org/',
    },
    {
        label: 'Aerospike',
        quadrant: 3,
        ring: 2,
        link: 'https://aerospike.com/',
    },
    {
        label: 'Ignite',
        quadrant: 3,
        ring: 2,
        link: 'https://ignite.apache.org/',
    },
    {
        label: 'InfluxDB',
        quadrant: 3,
        ring: 2,
        link: 'https://www.influxdata.com/',
    },
    {
        label: 'Greenplum',
        quadrant: 3,
        ring: 2,
        link: 'https://greenplum.org/',
    },
    {
        label: 'Redis',
        quadrant: 3,
        ring: 2,
        link: 'https://redis.io/',
    },
    {
        label: 'Tarantool',
        quadrant: 3,
        ring: 1,
        link: 'https://www.tarantool.io/ru/',
    },
    {
        label: 'ClickHouse',
        quadrant: 3,
        ring: 1,
        link: 'https://clickhouse.com/',
    },
    {
        label: 'Neo4j',
        quadrant: 3,
        ring: 2,
        link: 'https://neo4j.com/',
    },
    {
        label: 'ElasticSearch',
        quadrant: 3,
        ring: 0,
        link: 'https://www.elastic.co/',
    },
    {
        label: 'Prometheus',
        quadrant: 3,
        ring: 1,
        link: 'https://prometheus.io/',
    },
    {
        label: 'Jaeger',
        quadrant: 3,
        ring: 2,
        link: 'https://www.jaegertracing.io/',
    },
    {
        label: 'OpenTelemetry',
        quadrant: 3,
        ring: 2,
        link: 'https://opentelemetry.io/',
    },
    {
        label: 'MAPIC',
        quadrant: 3,
        ring: 2,
        link: '',
    },
    {
        label: 'NiFi',
        quadrant: 3,
        ring: 2,
        link: 'https://nifi.apache.org/',
    },
    {
        label: 'Nginx',
        quadrant: 3,
        ring: 0,
        link: 'https://opentelemetry.io/',
    },
    {
        label: 'Keycloak',
        quadrant: 3,
        ring: 1,
        link: 'https://www.keycloak.org/',
    },
    {
        label: 'HashiCorp Vault',
        quadrant: 3,
        ring: 2,
        link: 'https://www.vaultproject.io/',
    },
    {
        label: 'Tomcat',
        quadrant: 3,
        ring: 0,
        link: 'https://tomcat.apache.org/',
    },
    {
        label: 'Apache',
        quadrant: 3,
        ring: 0,
        link: '',
    },
    {
        label: 'Caddy',
        quadrant: 3,
        ring: 2,
        link: 'https://caddyserver.com/',
    },
    {
        label: 'IIS',
        quadrant: 3,
        ring: 3,
        link: 'https://www.iis.net/',
    },
    {
        label: 'VM Linux',
        quadrant: 3,
        ring: 0,
        link: '',
    },
    {
        label: 'VM Windows',
        quadrant: 3,
        ring: 3,
        link: '',
    },
    {
        label: 'Docker',
        quadrant: 3,
        ring: 0,
        link: '',
    },
    {
        label: 'Kubernetes',
        quadrant: 3,
        ring: 0,
        link: 'https://kubernetes.io',
    },
    {
        label: 'Harbor',
        quadrant: 3,
        ring: 1,
        link: 'https://goharbor.io/',
    },
    {
        label: 'Nexus OSS',
        quadrant: 3,
        ring: 1,
        link: 'https://www.sonatype.com/products/nexus-repository',
    },
    {
        label: 'Jenkins',
        quadrant: 2,
        ring: 3,
        link: 'https://www.jenkins.io/',
    },
    {
        label: 'Gitlab CI',
        quadrant: 2,
        ring: 0,
        link: 'https://docs.gitlab.com/ee/ci/',
    },
    {
        label: 'Teamcity',
        quadrant: 3,
        ring: 3,
        link: 'https://www.jetbrains.com/ru-ru/teamcity/',
    },
    {
        label: 'GitLab CE',
        quadrant: 3,
        ring: 1,
        link: 'https://gitlab.com/',
    },
    {
        label: 'SonarQube',
        quadrant: 3,
        ring: 3,
        link: 'https://www.sonarqube.org/',
    },
    {
        label: 'Consul',
        quadrant: 3,
        ring: 3,
        link: 'https://www.consul.io/',
    },
    {
        label: 'Istio',
        quadrant: 3,
        ring: 2,
        link: 'https://istio.io/',
    },
    {
        label: 'Ubuntu',
        quadrant: 3,
        ring: 0,
        link: 'https://ubuntu.com',
    },
    {
        label: 'CentOS',
        quadrant: 3,
        ring: 1,
        link: 'https://www.centos.org/',
    },
    {
        label: 'Oracle Linux',
        quadrant: 3,
        ring: 3,
        link: 'https://www.oracle.com/cis/linux/',
    },
    {
        label: 'Rocky Linux',
        quadrant: 3,
        ring: 2,
        link: 'https://rockylinux.org/ru/',
    },
    {
        label: 'Alpine Linux',
        quadrant: 3,
        ring: 2,
        link: 'https://alpinelinux.org',
    },
    {
        label: 'HA/DR Tools',
        quadrant: 3,
        ring: 0,
        link: '',
    },
    {
        label: 'NetBackup',
        quadrant: 2,
        ring: 0,
        link: '',
    },
    {
        label: 'VMware vSphere',
        quadrant: 3,
        ring: 0,
        link: '',
    },
    {
        label: 'OpenStack',
        quadrant: 3,
        ring: 1,
        link: 'https://www.openstack.org/',
    },
    {
        label: 'Firewall (L4-L7)',
        quadrant: 3,
        ring: 0,
        link: '',
    },
    {
        label: 'HDFS',
        quadrant: 3,
        ring: 1,
        link: '',
    },
    {
        label: 'Hive',
        quadrant: 3,
        ring: 1,
        link: '',
    },
    {
        label: 'Ceph',
        quadrant: 3,
        ring: 1,
        link: 'https://ceph.io/en/',
    },
    {
        label: 'S3',
        quadrant: 3,
        ring: 2,
        link: '',
    },
    {
        label: 'GlusterFS',
        quadrant: 3,
        ring: 2,
        link: '',
    },
    {
        label: 'Ansible',
        quadrant: 2,
        ring: 0,
        link: 'https://www.ansible.com/',
    },
    {
        label: 'Terraform',
        quadrant: 2,
        ring: 0,
        link: 'https://www.terraform.io/',
    },
    {
        label: 'x86 Arch',
        quadrant: 3,
        ring: 0,
        link: '',
    },
    {
        label: 'Java 8',
        quadrant: 1,
        ring: 3,
        link: '',
    },
    {
        label: 'Java 11 LTS',
        quadrant: 1,
        ring: 0,
        link: '',
    },
    {
        label: 'C++',
        quadrant: 1,
        ring: 0,
        link: '',
    },
    {
        label: '.NET Core 6 LTS',
        quadrant: 1,
        ring: 0,
        link: '',
    },
    {
        label: 'Lua',
        quadrant: 1,
        ring: 0,
        link: '',
    },
    {
        label: 'Node.js',
        quadrant: 1,
        ring: 0,
        link: '',
    },
    {
        label: 'Spring',
        quadrant: 1,
        ring: 0,
        link: '',
    },
    {
        label: 'Spring Boot',
        quadrant: 1,
        ring: 0,
        link: '',
    },
    {
        label: 'Liquibase',
        quadrant: 2,
        ring: 0,
        link: '',
    },
    {
        label: 'PHP',
        quadrant: 1,
        ring: 3,
        link: '',
    },
    {
        label: 'Erlang',
        quadrant: 1,
        ring: 3,
        link: '',
    },
    {
        label: 'jQuery',
        quadrant: 1,
        ring: 3,
        link: '',
    },
    {
        label: 'React',
        quadrant: 1,
        ring: 0,
        link: '',
    },
    {
        label: 'Angular',
        quadrant: 1,
        ring: 3,
        link: '',
    },
    {
        label: 'TypeScript',
        quadrant: 1,
        ring: 1,
        link: '',
    },
    {
        label: 'Webpack',
        quadrant: 1,
        ring: 1,
        link: '',
    },
    {
        label: 'Remix',
        quadrant: 1,
        ring: 0,
        link: '',
    },
    {
        label: 'Next.js',
        quadrant: 1,
        ring: 0,
        link: '',
    },
    {
        label: 'Eleventy',
        quadrant: 1,
        ring: 2,
        link: '',
    },
    {
        label: 'GatsbyJS',
        quadrant: 1,
        ring: 3,
        link: '',
    },
    {
        label: 'React Native',
        quadrant: 1,
        ring: 2,
        link: '',
    },
    {
        label: 'xUnit',
        quadrant: 2,
        ring: 2,
        link: '',
    },
    {
        label: 'SoapUI',
        quadrant: 2,
        ring: 2,
        link: '',
    },
    {
        label: 'LoadUI',
        quadrant: 2,
        ring: 2,
        link: '',
    },
    {
        label: 'Chaos Monkey',
        quadrant: 2,
        ring: 2,
        link: '',
    },
    {
        label: 'Cucumber',
        quadrant: 2,
        ring: 2,
        link: '',
    },
    {
        label: 'Selenium',
        quadrant: 2,
        ring: 2,
        link: '',
    },
    {
        label: 'Jest',
        quadrant: 1,
        ring: 0,
        link: '',
    },
    {
        label: 'Helm',
        quadrant: 2,
        ring: 0,
        link: '',
    },
    {
        label: 'Octopus Deploy',
        quadrant: 2,
        ring: 3,
        link: '',
    },
    {
        label: 'argoCD',
        quadrant: 2,
        ring: 2,
        link: 'https://argo-cd.readthedocs.io/',
    },
    {
        label: 'BeeWorks',
        quadrant: 2,
        ring: 1,
        link: '',
    },
    {
        label: 'Zabbix',
        quadrant: 2,
        ring: 0,
        link: 'https://www.zabbix.com/ru/index',
    },
    {
        label: 'Grafana',
        quadrant: 2,
        ring: 0,
        link: 'https://grafana.com/',
    },
    {
        label: 'MS SCOM',
        quadrant: 2,
        ring: 0,
        link: '',
    },
    {
        label: 'ELK',
        quadrant: 2,
        ring: 1,
        link: '',
    },
    {
        label: 'Sentry',
        quadrant: 2,
        ring: 2,
        link: 'https://sentry.io/',
    },
    {
        label: 'Prometheus',
        quadrant: 2,
        ring: 1,
        link: 'https://prometheus.io/',
    },
    {
        label: 'MS DNS',
        quadrant: 3,
        ring: 0,
        link: '',
    },
    {
        label: 'MS Exchange',
        quadrant: 3,
        ring: 0,
        link: '',
    },
    {
        label: 'MS AD',
        quadrant: 3,
        ring: 0,
        link: '',
    },
    {
        label: 'Remedy BMC',
        quadrant: 3,
        ring: 0,
        link: '',
    },
    {
        label: 'Confluence',
        quadrant: 3,
        ring: 0,
        link: 'https://www.atlassian.com/software/confluence',
    },
    {
        label: 'Jira',
        quadrant: 3,
        ring: 0,
        link: 'https://www.atlassian.com/ru/software/jira',
    },
    {
        label: 'Slack',
        quadrant: 3,
        ring: 3,
        link: 'https://slack.com/',
    },
    {
        label: 'Kaspersky',
        quadrant: 3,
        ring: 1,
        link: '',
    },
    {
        label: 'CD',
        quadrant: 0,
        ring: 0,
        link: '',
    },
    {
        label: 'CI',
        quadrant: 0,
        ring: 0,
        link: '',
    },
    {
        label: 'Doc as a code',
        quadrant: 0,
        ring: 2,
        link: '',
    },
    {
        label: 'Arch as a code',
        quadrant: 0,
        ring: 2,
        link: '',
    },
    {
        label: 'Microservices',
        quadrant: 0,
        ring: 0,
        link: '',
    },
    {
        label: 'OAuth',
        quadrant: 0,
        ring: 0,
        link: '',
    },
    {
        label: 'SOLID',
        quadrant: 0,
        ring: 1,
        link: '',
    },
    {
        label: 'TMF Open API',
        quadrant: 0,
        ring: 0,
        link: '',
    },
    {
        label: 'TMF ODA',
        quadrant: 0,
        ring: 0,
        link: '',
    },
    {
        label: 'Zero downtime (ZDD)',
        quadrant: 0,
        ring: 2,
        link: '',
    },
    {
        label: 'OWASP',
        quadrant: 0,
        ring: 2,
        link: '',
    },
    {
        label: 'REST',
        quadrant: 0,
        ring: 0,
        link: '',
    },
    {
        label: 'Distroless Docker',
        quadrant: 0,
        ring: 2,
        link: '',
    },
    {
        label: 'Zero Trust Arch (ZTA)',
        quadrant: 0,
        ring: 2,
        link: '',
    },
    {
        label: 'Micro frontend',
        quadrant: 0,
        ring: 2,
        link: '',
    },
    {
        label: 'Product-Service',
        quadrant: 0,
        ring: 0,
        link: '',
    },
    {
        label: 'Observability',
        quadrant: 0,
        ring: 1,
        link: '',
    },
    {
        label: 'Digital Pipeline',
        quadrant: 0,
        ring: 2,
        link: '',
    },
    {
        label: 'Data Model',
        quadrant: 0,
        ring: 1,
        link: '',
    },
    {
        label: 'Tech debt mgmt',
        quadrant: 0,
        ring: 2,
        link: '',
    },
    {
        label: 'Mobile First',
        quadrant: 0,
        ring: 2,
        link: '',
    },
];
